### ISSUE TITLE
Hooold up a second, Is the readme the Goals or current state?

### ISSUE THREAD

**Issue by michaelsakharov** [reignstudios/Orbital-Framework#2]
Is the Readme the Goal of the project? If not where's the project currently at?
With Veldrid's main dev gone, there are not really any other pure c# API Agnostic libraries like it.
Except this? I'm working on a game engine and have been considering using Veldrid but if the readme is accurate this looks insane.
The only other alternative I'm looking at is BGFX but that's just graphics and has a weird View-order drawing thingy that's making it more difficult to port my engine to it.

I imagine its just the goals?

**Comment by zezba9000** [comment]
> Is the Readme the Goal of the project?

Correct. Right now D3D12 is working and some Vulkan. In the past on an older outdate project I used to support D3D9,10,11, OpenGL, etc. This project is also going to start getting more work here soon after the Unity3D fallout. I'm just prepping some things before I start getting back into it.

I also plan on using Orbital framework as the base of a pure C# GPL game-engine with IDE & the works thats extremely portable.

**Comment by michaelsakharov** [comment]
Yeah ok, Got super excited that this was that far along.

I'm also working on a pure c# game engine now (Unity re-implementation essentially), just finished the Asset pipeline, and am planning to make it MIT Licenced.
After yeah the Unity fallout I need a replacement, haha, Currently looking at graphics libraries, it is between Veldrid, BGFX, Pie, this, and making my own. There's also the option of building on top of an existing game framework Raylib but that feels like cheating haha.

**Comment by zezba9000** [comment]
@michaelsakharov Ya wish I never put this project off for Unity Render Pipeline stuff.
My long term plan is Game-Engine IDE being GPL but all source code used to builds etc will be MIT.

Just follow this project if you want as I do plan on getting more stuff working. Modern platforms will be targeted first of course.
